FC = eSC
C = Coefficient matrix. Rows are atomic orbitals and columns are molecular orbitals
F is Fock-operator constituting of electron kinetic energy(T), Nuclear_electron repulsion, and electron-electron repulsion
F = T + V_NE + V_EE
S = overlap matrix (rows and columns will be our basis functions, just a series of primitive gaussian functions
We will first do H2 (only s orbitals) and then H2O

In [7]:
import sys
import numpy as np
import math

In [12]:
class PrimitiveGaussian:
    def __init__ (self, alpha, contraction_coefficient, coordinates, l1, l2, l3): #l1,l2,l3 are angular momentum, they do not exist for s-orbitals
        self.alpha = alpha
        self.contraction_coefficient = contraction_coefficient
        self.coordinates = np.array(coordinates)
        self.A = (2.0 * alpha/math.pi)**0.75 #plus l1, l2, l3 whenever present #A is normalization constant

In [17]:
def overlap(molecule):
    nbasis = len(molecule) #this is going to be two
    #S will be a two by two zeroes matrix
    S = np.zeros([nbasis, nbasis])
    #now we need to loop over each basis function
    for i in range(nbasis):
        for j in range(nbasis):
            
            nprimitives_i = len(molecule[i])
            nprimitives_j = len(molecule[j])

            for k in range(nprimitives_i):
                for l in range(nprimitives_j):
                    #multiplying normalization constants to get the overall normalization constant
                    N = molecule[i][k].A * molecule[j][l].A
                    p = molecule[i][k].alpha + molecule[j][l].alpha
                    q = molecule[i][k].alpha * molecule[j][l].alpha / p
                    Q = molecule[i][k].coordinates - molecule[j][l].coordinates
                    Q2 = np.dot(Q,Q) #dot product
                    
                    S[i,j] += N * molecule[i][k].contraction_coefficient * molecule[j][l].contraction_coefficient * math.exp(-q*Q2) * (math.pi/p)**(3/2)
    return S

In [20]:
#define H1_1s
#Used Basis Set Exchange to get the primitive gaussian sets for each
#STO-3G s-orbitals on Hydrogen.
#The two hydrogens are along x-axis at x=0 and x = 1.2
H1_pga = PrimitiveGaussian(0.3425250914E+01, 0.1543289673E+00, [0,0,0], 0, 0, 0)
H1_pgb = PrimitiveGaussian(0.6239137298E+00, 0.5353281423E+00, [0,0,0], 0, 0, 0)
H1_pgc = PrimitiveGaussian(0.1688554040E+00, 0.4446345422E+00, [0,0,0], 0, 0, 0)
H2_pga = PrimitiveGaussian(0.3425250914E+01, 0.1543289673E+00, [1.2,0,0], 0, 0, 0)
H2_pgb = PrimitiveGaussian(0.6239137298E+00, 0.5353281423E+00, [1.2,0,0], 0, 0, 0)
H2_pgc = PrimitiveGaussian(0.1688554040E+00, 0.4446345422E+00, [1.2,0,0], 0, 0, 0)
H1_1s = [H1_pga, H1_pgb, H1_pgc]  #pg is for primitive gaussian,
H2_1s = [H2_pga, H2_pgb, H2_pgc]   #Using STO-3G basis sets
molecule = [H1_1s, H2_1s] #Hydrogen molecule constituting of hydrogen 1 and hydrogen 2 both which have 1s orbitals [Just two basis functions, each centered on each hydrogen and each is based on basis functions
print(f"""
STO3G Overlap_Matrix: 

{overlap(molecule)}
""")

###########################
###########################

#6-31G basis for 1s and 2s orbitals on hydrogen
#satrt backwards as always
H1_pga = PrimitiveGaussian(0.1873113696E+02, 0.3349460434E-01, [0,0,0], 0, 0, 0)
H1_pgb = PrimitiveGaussian(0.2825394365E+01, 0.2347269535E+00, [0,0,0], 0, 0, 0)
H1_pgc = PrimitiveGaussian(0.6401216923E+00, 0.8137573261E+00, [0,0,0], 0, 0, 0)
H2_pga = PrimitiveGaussian(0.1873113696E+02, 0.3349460434E-01, [1.2,0,0], 0, 0, 0)
H2_pgb = PrimitiveGaussian(0.2825394365E+01, 0.2347269535E+00, [1.2,0,0], 0, 0, 0)
H2_pgc = PrimitiveGaussian(0.6401216923E+000, 0.8137573261E+00, [1.2,0,0], 0, 0, 0)
H1_pg2a = PrimitiveGaussian(0.1612777588E+00, 1.0000000, [0,0,0], 0, 0, 0)
H2_pg2a = PrimitiveGaussian(0.1612777588E+00, 1.0000000, [1.2,0,0], 0, 0, 0)
H1_1s = [H1_pga, H1_pgb, H1_pgc]
H1_2s = [H1_pg2a]
H2_1s = [H1_pga, H1_pgb, H1_pgc]
H2_2s = [H2_pg2a]
molecule = [H1_1s, H1_2s, H2_1s, H2_2s] #meaning we will now have four basis functions



print(f"""
6-31G Overlap_Matrix: 

{overlap(molecule)}
""")


STO3G Overlap_Matrix: 

[[1.         0.72864938]
 [0.72864938 1.        ]]


6-31G Overlap_Matrix: 

[[1.         0.65829197 1.         0.54474596]
 [0.65829197 1.         0.65829197 0.89036838]
 [1.         0.65829197 1.         0.54474596]
 [0.54474596 0.89036838 0.54474596 1.        ]]

